### ISSUE TITLE
master control 

### ISSUE THREAD

**Issue by LCKway** [lnsru/melexis_VGA_ToF_camera#6]
What is your master control

**Comment by lnsru** [comment]
??? I think, you want to hear this: FPGA

**Comment by LCKway** [comment]
I wouldn't use

The big guy taught me

**Comment by lnsru** [comment]
> 
> 
> I wouldn't use
> 
> The big guy taught me

What would you use?

**Comment by LCKway** [comment]
raspberry       
I can't use a “MLX_TOF_75027”
but i want to  make it "tof_camera"
Can you teach me?

**Comment by lnsru** [comment]
I hope, you can buy it later from me :-)

**Comment by LCKway** [comment]
Are you a commodity already?

**Comment by LCKway** [comment]
Are you a commodity already?

**Comment by lnsru** [comment]
I hope, next year. There are still some unfinished tasks

**Comment by LCKway** [comment]
in other words
So you're not done yet?

**Comment by lnsru** [comment]
Exactly! I am not done yet.

**Comment by LCKway** [comment]
I'm just starting to make it now
I don't know if I can finish it before I graduate from college
I don't have any references to this stuff on my side

**Comment by lnsru** [comment]
Layout works except inverted flat cable connector. Power supply might be also better, but that's already an optimization steps.
